language: python
python:
  - "3.8"
install:
  - python -m pip install poetry
  - python -m pip install flake8
  - python -m pip install -U pytest
  - python -m pip install coverage
  - python -m pip install pytest-cov

