name: Lint and Test
on: push


jobs:
  project3:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install flake8
          python -m pip install -U pytest
          python -m pip install coverage
          python -m pip install pytest-cov

      - name: Poetry Install
        run: make install

      - name: Run flake8 lint
        run: make lint

      - name: Before Test
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run pytest
        run: make test

      - name: After script
        env:
          CC_TEST_REPORTER_ID: ${{ 377f431bc8679f70ddc228cc99dff7617fe06d6ee5906a9bad32b426b4f6072b }}
        run: |
          poetry run coverage xml
          ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $TRAVIS_TEST_RESULT