name: Lint and Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install flake8
          python -m pip install -U pytest
          python -m pip install coverage
          python -m pip install pytest-cov

      - name: Poetry Install
        run: make install

      - name: Run flake8 lint
        run: make lint

      - name: Run pytest
        run: make test